apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-devops
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "configMaps", "secrets", "nodes", "namespaces", "events", "serviceAccounts"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]